### ISSUE TITLE
"topologies" is used before defined

### ISSUE THREAD

**Issue by Hang-Zhang** [jhbastek/VideoMetamaterials#1]
In "video_denoising_diffusion_pytorch.py"

for i in range(1,4):
    tensor[i,:,:,:][topologies[0,:,:,:] == 0.] = 0.

"topologies" is used before defined.

**Comment by jhbastek** [comment]
Thank you for raising this, during streamlining the code I accidentally deleted the line where `topologies` is defined. I have fixed this with the newest push.
