### ISSUE TITLE
How to rescale the pixel values to their physical equivalent during inference?

### ISSUE THREAD

**Issue by Hang-Zhang** [jhbastek/VideoMetamaterials#3]
I wonder how to rescale the pixel values to their physical equivalent for the gifs generated during inference.

As the codes write in the Dataset class, we first need to "unorm" the grey gifs based on "frame_range_data", then set values to zero for all pixels where topology is zero, lastly, "normalize" the tensors to global range based on "min_max_values".

Although, the "min_max_values" during training can be used, we can not get the corresponding information on "frame_range_data" during inference. Could you please explain more on how to get the displacement/stress distribution during inference?

Thanks very much for your time!

**Comment by jhbastek** [comment]
For the data loading, we first unnormalize the gif data to their true value (e.g., von-Mises stress in MPa) and then normalize these to [0,1] based on the minimum and maximum values of the whole training dataset. This is then passed to the model during training. The model then makes predictions based on this normalization, and thus, to get back to the true values, we must unnormalize these values based on the global (training data) range. 
As mentioned in the REAMDE, we supply the (global) normalization constants to rescale the pixel values to their physical equivalent in `data/<reference_frame>/training/min_max_values.csv`. Hope this clarifies things!

**Comment by Hang-Zhang** [comment]
I can not find the min_max_values.csv either here or in the dataset in ETHZ Research Collection.

By the way, how to generate the min_max_values.csv?

**Comment by Hang-Zhang** [comment]
Is it the one generated during training?

**Comment by jhbastek** [comment]
These will be generated if you run the script (more precisely, after initialization of the Trainer class, see line 1209-1219 in `/denoising_diffusion_pytorch/video_denoising_diffusion_pytorch.py`).

**Comment by Hang-Zhang** [comment]
Got it. I will try again. Thanks very much!

**Comment by jhbastek** [comment]
No problem!
