### ISSUE TITLE
Script for merging the 3 channel gifs

### ISSUE THREAD

**Issue by nbbllxx0** [jhbastek/VideoMetamaterials#4]
Hi there, I wonder if there is an official script could transform the 3 one channel gifs into one, those gifs are basically greyscale, unlike the figures in the paper.

**Comment by jhbastek** [comment]
The colored gifs in the paper are just individual channels / grayscale gifs but converted via a colormap for better legibility, so this is fairly straightforward. I will try to add some more postprocessing scripts in the next weeks, but currently am a bit on a tight schedule. If you are highly interested, just send me an email (jbastek@ethz.ch) and I can provide you with some preliminary code.

**Comment by feiji110** [comment]
Great Job! Here I wonder if there is an official script could transform Euler Format from Lagranian format which is the model predict in the paper?

**Comment by jhbastek** [comment]
I have just pushed the scripts to convert the raw gifs to the ones shown in the paper. Hope this helps!
